const
{help file names}
  HelpEng = 'tterm.hlp';
  HelpJpn = 'ttermj.hlp';

{help context numbers}
const
  HlpFileNewConnection = 1;
  HlpFileLog = 2;
  HlpFileSend = 3;
  HlpFileKmtGet = 4;
  HlpFileKmtSend = 5;
  HlpFileXmodemRecv = 6;
  HlpFileXmodemSend = 7;
  HlpFileZmodemSend = 8;
  HlpFileBPlusSend = 9;
  HlpFileQVSend = 10;
  HlpFileChangeDir = 11;
  HlpFilePrint = 12;
  HlpSetupTerminal = 13;
  HlpSetupTerminalRuss = 14;
  HlpSetupWindow = 15;
  HlpSetupFont = 16;
  HlpSetupFontRuss = 17;
  HlpSetupKeyboard = 18;
  HlpSetupKeyboardRuss = 19;
  HlpSetupSerialPort = 20;
  HlpSetupTCPIP = 21;
  HlpSetupGeneral = 22;
  HlpSetupSave = 23;
  HlpSetupRestore = 24;
  HlpSetupLoadKeyMap = 25;
  HlpWindowWindow = 26;
  HlpTEKFilePrint = 27;
  HlpTEKSetupWindow = 28;
  HlpTEKSetupFont = 29;
